### PR TITLE
add institution field

### PR DESCRIPTION
**Pull request by spacemansteve**

### CODE REVIEW

**Comment by aaccomazzi** [comment]
Not an expert, but it seems to me that the tokenizers are not defined correctly.  They are basic text ones, which will break things up on whitespace, use synonyms, acronyms, etc.  This will not accomplish the search requirements listed in this issue: https://github.com/romanchyla/montysolr/issues/126

For instance, searching for `institution:"Dep"` should return nothing ("Dep" is not a canonical abbreviation), but it will as defined (it does now for `aff_abbrev`).

**Comment by romanchyla** [comment]
Could you remind me please how the parsing was intended?

My recollection is the following: 'parent/child somewhere foo bar/

and they should be indexed as:

parent
child somewhere foo bar

not as:

parent
child
somewhere
foo
bar

is that right? @aaccomazzi or @spacemansteve

**Comment by aaccomazzi** [comment]
@romanchyla that is correct.  Again, the full description is here: https://github.com/romanchyla/montysolr/issues/126
This should probably be marked as a duplicate.

**Comment by romanchyla** [comment]
ok, sorry for the delay in commenting...

as @aaccomazzi said the tokenizer chain will need some modifications; it should break on '/' as similar ones using regex; with the standard lowercasing in the mix

so this needs simplification: https://github.com/romanchyla/montysolr/blob/6feaad7a9c922d8a6574bd4ef1c3c70db56eace0/contrib/examples/adsabs/server/solr/collection1/conf/schema.xml#L852

and all the other elements, besides lowercasing and trimming and de-deplication should be removed

@spacemansteve please also add a test case indexing 'foo/bar baz' and search for:

foo -> 1
bar baz -> 1
foo/bar baz -> 1
foo bar -> 0

**Comment by romanchyla** [comment]
@spacemansteve did you perhaps forgot to include your latest changes? I don't see them

**Pull request closed without merging**
